app/controllers/products_controller.rb
app/models/product.rb
app/models/user.rb
app/views/products/index.html.erb
config/routes.rb

estruturação do products controller finalizado  Autorização e autendicação pendentes

Controllers

---

app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

crapy log-in structure - to be improved

log in page structure

---

app/views/products/show.html.erb

product-show view structure created

product-show view structure created

---

app/controllers/users_controller.rb
test/controllers/users_controller_test.rb

user controller with destroy and field validation on create

---

app/controllers/users_controller.rb
config/routes.rb

updated controller with methods

updatede controller-user with methods

---

app/views/devise/sessions/new.html.erb

Reverts alexandrecastello/rails-medieval-market#18

Revert "Layout for sign in"

---

app/controllers/users_controller.rb
app/views/users/_my_items.html.erb
app/views/users/show.html.erb

created page for a user page (logged in) - should show user products, amount and permit the user to destroy a product (if he wants to). should show product price and allow edit its price.

User products

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb

changes for a functionable signup/login - crappy scss (please review and stage changes if wished)

changes on appl_cont pages_cont sessions/new and appl.html 

---

app/views/devise/passwords/edit.html.erb
app/views/devise/registrations/edit.html.erb
app/views/users/show.html.erb

please take this page with a grain of salt - no styling

links to home and products pages from logged user page

---

app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb

Layout for the signup page

---

app/views/products/index.html.erb
app/views/products/show.html.erb
app/views/users/_my_items.html.erb

index has no path to products - waiting for limited-list method

paths added on index show and my items

---

app/controllers/pages_controller.rb
app/controllers/products_controller.rb
app/views/products/edit.html.erb
app/views/shared/_edit.html.erb
app/views/shared/_recent_products.html.erb
config/routes.rb

Product-edit-view created + recent_products created

Product-edit-view created + recent_products created

---

app/views/products/index.html.erb
app/views/products/new.html.erb
app/views/products/show.html.erb

navbar fix on pro/show pro/new and pro/index

navbar fix on pro/show pro/new and pro/index

---

app/views/devise/sessions/new.html.erb

Fixes on login page

---

app/views/devise/passwords/new.html.erb

comply forgot password page with other devise pages
@mbourg =>
no footbar on this commit
button not aligned

comply forgot password page with other devise pages

---

app/views/pages/home.html.erb

prod price with marker

---

app/controllers/orders_controller.rb
app/controllers/products_controller.rb
app/views/products/show.html.erb

buying and paying with coins works now"

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/products/index.html.erb
app/views/products/new.html.erb

footer at bottom, relative to container, at all pages

footer relative at bottom to all pages

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/views/products/index.html.erb

background color to soft-white,
search results on products page comply to homepage style (search bar now appears)
search engine working on products page on products page itself

Search results edited

---

app/assets/stylesheets/pages/_home.scss

cards are now really cards. border and background added

cards basic styling with border radius and background color

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/models/product.rb
app/views/pages/home.html.erb
app/views/products/index.html.erb
app/views/products/new.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20200605141954_create_active_storage_tables.active_storage.rb
db/schema.rb

images from Cloudinary are not responsive

Cloudinary appli

---

app/views/products/show.html.erb

product sell page now pulls product image from db.
if no image is added, standard image shows up

add product image on product sell page
